--  This is the version for OpenVMS

with Interfaces.C;
with System.Storage_Elements;

package System.OS_Constants is

   AF_INET                       : constant := 2;
   AF_INET6                      : constant := 10;
   Need_Netdb_Buffer             : constant := 1;
   Need_Netdb_Lock               : constant := 0;
   IPPROTO_IP                    : constant := 0;
   IPPROTO_UDP                   : constant := 17;
   IPPROTO_TCP                   : constant := 6;
   SO_REUSEADDR                  : constant := 2;
   SO_REUSEPORT                  : constant := -1;
   SO_KEEPALIVE                  : constant := 9;
   SO_LINGER                     : constant := 13;
   SO_BROADCAST                  : constant := 6;
   SO_SNDBUF                     : constant := 7;
   SO_RCVBUF                     : constant := 8;
   SO_SNDTIMEO                   : constant := 21;
   SO_RCVTIMEO                   : constant := 20;
   SO_ERROR                      : constant := 4;
   SIZEOF_sockaddr_in            : constant := 16;
   SIZEOF_sockaddr_in6           : constant := 28;
   FD_SETSIZE                    : constant := 1024;
   SIZEOF_struct_hostent         : constant := 32;
   SIZEOF_struct_servent         : constant := 32;
   SIZEOF_sigset                 : constant := 128;
   MSG_OOB                       : constant := 1;
   MSG_PEEK                      : constant := 2;
   MSG_EOR                       : constant := 128;
   MSG_WAITALL                   : constant := 256;
   MSG_NOSIGNAL                  : constant := 16384;
   subtype Msg_Iovlen_T is Interfaces.C.size_t;
   MSG_Forced_Flags              : constant := MSG_NOSIGNAL;
   SIZEOF_tv_sec                 : constant := 8;
   SIZEOF_tv_usec                : constant := 8;

   SOL_SOCKET  : constant := 1;
   SOCK_STREAM : constant := 2;
   SOCK_DGRAM  : constant := 3;
   SHUT_RD     : constant := 4;
   SHUT_WR     : constant := 5;
   SHUT_RDWR   : constant := 6;
   TCP_NODELAY : constant := 7;
   IP_ADD_MEMBERSHIP : constant := 1;
   IP_DROP_MEMBERSHIP : constant := 1;
   IP_MULTICAST_IF : constant := 1;
   IP_MULTICAST_TTL : constant := 1;
   IP_MULTICAST_LOOP : constant := 1;
   IP_PKTINFO : constant := 1;
   Thread_Blocking_IO : constant Boolean := True;
   Has_Sockaddr_Len              : constant := 0;
   HOST_NOT_FOUND : constant := 1;
   TRY_AGAIN : constant := 2;
   NO_RECOVERY : constant := 3;
   NO_DATA : constant := 4;

   Inet_Pton_Linkname : constant String := "undefined_symbol_in_soscons";
   MAX_tv_sec                    : constant Duration := 1.0;
   --  Added by adalabs for GNAT.Sockets (ads)
   SIZEOF_fd_set : constant System.Storage_Elements.Storage_Offset := 1024;
   --  Added by adalabs for GNAT.Sockets (ads)
   PTY_Library                   : constant String := "";
   --  Added by adalabs for GNAT.Expect.TTY (adb)

   type OS_Type is (Windows, VMS, Other_OS);
   Target_OS                     : constant OS_Type := VMS;
   Target_Name                   : constant String  := "OpenVMS";
   SIZEOF_unsigned_int           : constant := 4;
   SIZEOF_struct_file_attributes : constant := 20;
   SIZEOF_struct_dirent_alloc    : constant := 256;
   IOV_MAX                       : constant := 16;
   NAME_MAX                      : constant := 255;
   FILENAME_MAX                  : constant := 256;
   O_RDWR                        : constant := 2;
   O_NOCTTY                      : constant := 4096;
   O_NDELAY                      : constant := -1;
   F_GETFL                       : constant := 3;
   F_SETFL                       : constant := 4;
   FNDELAY                       : constant := -1;
   subtype IOCTL_Req_T is Interfaces.C.int;
   FIONBIO                       : constant := -2147195266;
   FIONREAD                      : constant := 1074030207;
   EAGAIN                        : constant := 11;
   ENOENT                        : constant := 2;
   ENOMEM                        : constant := 12;
   EACCES                        : constant := 13;
   EADDRINUSE                    : constant := 48;
   EADDRNOTAVAIL                 : constant := 49;
   EAFNOSUPPORT                  : constant := 47;
   EALREADY                      : constant := 37;
   EBADF                         : constant := 9;
   ECONNABORTED                  : constant := 53;
   ECONNREFUSED                  : constant := 61;
   ECONNRESET                    : constant := 54;
   EDESTADDRREQ                  : constant := 39;
   EFAULT                        : constant := 14;
   EHOSTDOWN                     : constant := 64;
   EHOSTUNREACH                  : constant := 65;
   EINPROGRESS                   : constant := 36;
   EINTR                         : constant := 4;
   EINVAL                        : constant := 22;
   EIO                           : constant := 5;
   EISCONN                       : constant := 56;
   ELOOP                         : constant := 62;
   EMFILE                        : constant := 24;
   EMSGSIZE                      : constant := 40;
   ENAMETOOLONG                  : constant := 63;
   ENETDOWN                      : constant := 50;
   ENETRESET                     : constant := 52;
   ENETUNREACH                   : constant := 51;
   ENOBUFS                       : constant := 55;
   ENOPROTOOPT                   : constant := 42;
   ENOTCONN                      : constant := 57;
   ENOTSOCK                      : constant := 38;
   EOPNOTSUPP                    : constant := 45;
   EPIPE                         : constant := 32;
   EPFNOSUPPORT                  : constant := 46;
   EPROTONOSUPPORT               : constant := 43;
   EPROTOTYPE                    : constant := 41;
   ERANGE                        : constant := 34;
   ESHUTDOWN                     : constant := 58;
   ESOCKTNOSUPPORT               : constant := 44;
   ETIMEDOUT                     : constant := 60;
   ETOOMANYREFS                  : constant := 59;
   EWOULDBLOCK                   : constant := 35;
   E2BIG                         : constant := 7;
end System.OS_Constants;
